### ISSUE TITLE
please update requirements.txt to support edgegrid-python==1.1.1

### ISSUE THREAD

**Issue by javiergarza** [akamai/cli-visitor-prioritization#9]
can you please update requirements.txt, and change edgegrid-python==1.0.10 with edgegrid-python==1.1.1 ?

**Comment by aetsai** [comment]
Done in [08b6f22](https://github.com/akamai/cli-visitor-prioritization/commit/08b6f222fd86363af182fb6d15e3313269ba6147) and released with [v0.2.1](https://github.com/akamai/cli-visitor-prioritization/releases/tag/v0.2.1)
